### ISSUE TITLE
Old parameter doesn’t work 

### ISSUE THREAD

**Issue by p4rzival0ne** [Saudumm/scriptable-News-Widget#1]
Hi
Seems to be either the last update that the old parameter in .txt doesn’t work. 
My parameter is : large|Tech News.txt|Tech  News|true|LargeBG.jpg 

Can you check pls ?

**Comment by Saudumm** [comment]
Hi! I've replaced the old txt Settings with a new system (Settings Wizard).
I've updated the ReadMe with new instructions. Could you please check it and test your config with the new settings? Thanks :)

**Comment by p4rzival0ne** [comment]
Works !! tks
