### ISSUE TITLE
Not working with iOS 15

### ISSUE THREAD

**Issue by Pulsar2011** [Saudumm/scriptable-News-Widget#15]
Since I updated OS to iOS15, NEWS widget doesn't work any more. No error message to understand what is happenning. When manually runing the script from the scriptable app, the script seems to hang ...

**Comment by Saudumm** [comment]
Hi! There's currently an issue with Scriptable on iOS15: https://twitter.com/scriptableapp/status/1440206816336482309

I'll take a look at the code and check if there's anything I can do, but for now we'll have to wait for a Scriptable App update.

**Comment by Pulsar2011** [comment]
Thanks for the information. I wasn’t aware of that.

**Comment by Saudumm** [comment]
There's an update available for Scriptable in the AppStore. The widget should work again with this new version.
