### ISSUE TITLE
Background  image name / location

### ISSUE THREAD

**Issue by bradanlane** [Saudumm/scriptable-News-Widget#4]
I created a background image. Named it. Put it in the “Files App” under iCloud -> Scriptable but it never displays and no error message.

This is my confit variable:
`var BG_IMAGE_NAME = "middle-medium-background";`

The file does not have an extension.

Any suggestions on how to debug?

**Comment by Saudumm** [comment]
Are you sure it doesn't have an extension or is the extension simply not displayed in the Files App? Long press on the file and select info to display the full filename

**Comment by bradanlane** [comment]
Aha!

Even though I edited the name it still had an extension and - as you pointed - only by long press and selecting “info” did I see the actual fill file name.

**Comment by Saudumm** [comment]
Glad to be of help! :)
