### ISSUE TITLE
heise Security RSS funtioniert nicht

### ISSUE THREAD

**Issue by buarle** [Saudumm/scriptable-News-Widget#5]
Hi saudumm,

Danke für das coole widget.
Könntest du noch versuchen, den Heise Security RSS feed zum laufen zu bekommen.
Standard Heise funktioniert ja bereits.

https://www.heise.de/security/rss/news-atom.xml

Danke schon ma und schönen Sonntag noch!
Buarle

**Comment by Saudumm** [comment]
Hi! Bei mir funktioniert der Link, es werden nur keine Bilder angezeigt. Funktioniert der bei dir gar nicht?

**Comment by buarle** [comment]
Hi tut mir sehr leid. Ich hatte die version aus der App-Gallery welche noch 1.0.0 ist...
Hab das script manuel installiert und jetzt hab ich den gleichen stand wie du👍🏼

**Comment by buarle** [comment]
Falls es nicht viel Aufwand ist, wären die Bilder natürlich noch das Highlight. Kann aber ins backlog😉

**Comment by Saudumm** [comment]
Ich hab vor ca. zwei Wochen bereits ein Update an die Scriptable Galerie geschickt, aber leider wurde das immer noch nicht geändert. Die Version in der Galerie kam leider noch nicht mit Atom Feeds (wie z.B. von Heise) zurecht.
Ich hab mir den Security Feed nochmal genauer angesehen, aber leider hat hier Heise nirgends Bilder verlinkt, auf die ich zugreifen könnte, daher werden auch keine angezeigt :-/
