### ISSUE TITLE
news images not shown 

### ISSUE THREAD

**Issue by deroverda** [Saudumm/scriptable-News-Widget#6]
thanks for this script. 

I've added two .rss feeds and they're not showing any news images even though the news indeed have an image attached to the news when I check their websites. 

are there any pro/cons choosing .rs vs wordpress? could it be because I choose .rss I don't see pictures? 

bonus question: I'm currently running two rss feeds and I don't really understand exactly the difference between websites and date (CONF_DISPLAY_NEWS). what is the preferable choice? in what way does my news feed differ when I choose news or date? 

widget size: medium
settings: everything default
news feeds: 
https://www.svt.se/nyheter/rss.xml
http://feeds.bbci.co.uk/news/world/rss.xml

**Comment by Saudumm** [comment]
Hi! I've looked at both rss xml files and sadly, they don't have any image links in the feed, so there's nothing that the script can display. :-/

The difference between "news" and "date" is that sorting by date means that all news from all links are strictly sorted by date. If you have two or more feeds for your widget and one website posts many news per day and the other one doesn't, it's possible that only the news from this one website will be displayed (until the other one publishes something new). If you choose "website", the widget will always try to display at least one news per website, so you can always see the latest news per website.

**Comment by deroverda** [comment]
@Saudumm thanks for the clarification about the differences. And now I know I have to check if the feeds has pictures in them or not. For some reason I thought the images were fetched from the news source, my bad. You can close this.

**Comment by Saudumm** [comment]
Most RSS Readers will fetch images directly from the news, but that would probably be too much for an iOS widget if I had to load every website in the background and search for images, so I'm only searching for images in the rss file. :/ Sorry about that.
